services:
  frc-codex-server:
    image: frc-codex-server:latest
    depends_on:
      localstack:
        condition: service_healthy
      frc-codex-lambda:
        condition: service_healthy
    healthcheck:
      interval: 2s
      retries: 30
      test: curl localhost:8080/health --fail || exit 1
      timeout: 2s
    environment:
      ADMIN_ENABLED: "true"
      AWS: "false"
      AWS_ACCESS_KEY_ID: "local_aws_access_key_id"
      AWS_ENDPOINT_URL: "http://localstack.localhost:4566"
      AWS_ENDPOINT_URL_LAMBDA: "http://lambda.localhost:8080/"
      AWS_REGION: "eu-west-2"
      AWS_SECRET_ACCESS_KEY: "local_aws_secret_access_key"
      COMPANIES_HOUSE_DOCUMENT_API_BASE_URL: "https://document-api.companieshouse.gov.uk"
      COMPANIES_HOUSE_INFORMATION_API_BASE_URL: "https://api.companieshouse.gov.uk"
      COMPANIES_HOUSE_STREAM_API_BASE_URL: "https://stream.companieshouse.gov.uk"
      DB_PASSWORD: "frc_codex"
      DB_URL: "jdbc:postgresql://postgres.localhost:5432/frc_codex"
      DB_USERNAME: "frc_codex"
      FCA_DATA_API_BASE_URL: "https://data.fca.org.uk/artefacts/"
      FCA_SEARCH_API_URL: "https://api.data.fca.org.uk/search?index=fca-nsm-searchdata"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,address=*:8180,suspend=n"
      S3_RESULTS_BUCKET_NAME: "frc-codex-results"
      SQS_JOBS_QUEUE_NAME: "frc_codex_jobs"
      SQS_RESULTS_QUEUE_NAME: "frc_codex_results"
      SUPPORT_EMAIL: "support@arelle.org"
    secrets:
      - frc-codex-server.secrets
    ports:
      - 8080:8080
      - 8180:8180
  frc-codex-lambda:
    image: frc-codex-lambda:latest
    healthcheck:
      interval: 1s
      retries: 0
      test: exit 0 # TODO: Improve healthcheck
      timeout: 1s
    environment:
      AWS_ACCESS_KEY_ID: 'local_aws_access_key_id'
      AWS_ENDPOINT_URL: 'http://localstack.localhost:4566'
      AWS_SECRET_ACCESS_KEY: 'local_aws_secret_access_key'
      SECRETS_FILEPATH: '/run/secrets/frc-codex-server.secrets'
      S3_HTTP_CACHE_BUCKET_NAME: 'frc-codex-http-cache'
      S3_RESULTS_BUCKET_NAME: 'frc-codex-results'
      S3_REGION_NAME: 'eu-west-2'
    platform: linux/amd64
    ports:
      - 8081:8080
    networks:
      default:
        aliases:
          - lambda.localhost
    secrets:
      - frc-codex-server.secrets
  frc-codex-processor:
    profiles:
        - disabled
    image: frc-codex-processor:latest
    depends_on:
      localstack:
        condition: service_healthy
    healthcheck:
      interval: 1s
      retries: 0
      test: exit 0 # TODO: Improve healthcheck
      timeout: 1s
    environment:
      AWS_ACCESS_KEY_ID: 'local_aws_access_key_id'
      AWS_ENDPOINT_URL: 'http://localstack.localhost:4566'
      AWS_SECRET_ACCESS_KEY: 'local_aws_secret_access_key'
      MAXIMUM_PROCESSORS: '4'
      SECRETS_FILEPATH: '/run/secrets/frc-codex-server.secrets'
      SQS_REGION_NAME: 'eu-west-2'
      S3_HTTP_CACHE_BUCKET_NAME: 'frc-codex-http-cache'
      S3_RESULTS_BUCKET_NAME: 'frc-codex-results'
      S3_REGION_NAME: 'eu-west-2'
      SQS_JOBS_QUEUE_NAME: 'frc_codex_jobs'
      SQS_RESULTS_QUEUE_NAME: 'frc_codex_results'
    secrets:
      - frc-codex-server.secrets
    volumes:
      - ../tmp:/tmp
  localstack:
    image: localstack/localstack:3.4.0
    healthcheck:
      interval: 10s
      retries: 15
      test: curl localstack:4566/health || exit 1
      timeout: 4s
    environment:
      REGION_NAME: 'eu-west-2'
      S3_HTTP_CACHE_BUCKET_NAME: 'frc-codex-http-cache'
      S3_RESULTS_BUCKET_NAME: 'frc-codex-results'
      SUPPORT_EMAIL: 'support@arelle.org'
    ports:
      - 4566:4566
    networks:
      default:
        aliases:
          - localstack.localhost
    volumes:
      - ./localstack.sh:/etc/localstack/init/ready.d/script.sh
  postgres:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    environment:
      POSTGRES_DB: frc_codex
      POSTGRES_USER: frc_codex
      POSTGRES_PASSWORD: frc_codex
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - postgres.localhost
secrets:
  frc-codex-server.secrets:
    file: ../frc-codex-server.secrets
